finalized

diff --git a/.devops/deploy-pipelines.yml b/.devops/deploy-pipelines.yml
--- a/.devops/deploy-pipelines.yml
+++ b/.devops/deploy-pipelines.yml
@@ -330,15 +330,15 @@ stages:
                     GREEN_VERSION: $(app_version)
   # --- END Deploy UAT --- #
 
+  # --- START of Validate event in Hub (UAT) --- #
 
-  # --- START CDC Test suite in UAT --- #
   - stage: "UAT_Testing_Generate_Wallet_Event"
     displayName: "UAT Testing Generate Wallet Event"
-    dependsOn: [ ]
+    dependsOn: [ Deploy_UAT_Green]
     pool:
       vmImage: 'ubuntu-latest'
     jobs:
-      - job: api_tests_uat
+      - job: ValidateCDCFlow
         displayName: 'Run API Tests DataLake Flow (UAT)'
         steps:
           - script: |
@@ -352,7 +352,7 @@ stages:
           - script: |
               # Extract WALLET_ID from report JSON
               WALLET_ID=$(grep -oP "WALLET_ID=\K[^\']+" output.txt)
-
+              
               if [ -z "$WALLET_ID" ]; then
                 echo "WALLET_ID non trovato nel report."
                 exit 1
@@ -361,5 +361,40 @@ stages:
               echo "##vso[task.setvariable variable=WALLET_ID]$WALLET_ID"
             displayName: 'Extract and export WALLET_ID from JSON report'
 
-  # --- END of CDC Test suite in UAT --- #
+          - script: |
+              wget https://archive.apache.org/dist/kafka/2.8.0/kafka_2.13-2.8.0.tgz
+              tar -xzf kafka_2.13-2.8.0.tgz
+              export PATH=$PATH:$PWD/kafka_2.13-2.8.0/bin
+              # Verify Kafka installation
+              kafka-topics.sh --version
+              sleep 4
+
+              # Run the Kafka consumer command
+              eventsFromKafka=$(kafka-console-consumer.sh \
+                --bootstrap-server pagopa-u-itn-observ-evh.servicebus.windows.net:9093 \
+                --topic payment-wallet-ingestion-dl \
+                --from-beginning \
+                --timeout-ms 25000 \
+                --consumer-property sasl.mechanism=PLAIN \
+                --consumer-property security.protocol=SASL_SSL \
+                --consumer-property "sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=\"\$ConnectionString\" password=\"$(AZURE_EVENTHUB_CONNECTION_STRING)\";")
+              
+              # Print the latest event from Kafka
+              latestEvent=$(echo "$eventsFromKafka" | tail -n 1)
+
+              # Extract the id from the JSON string
+              eventId=$(echo $latestEvent | jq -r '.walletId')
+              expectedDataEventId=$WALLET_ID
+              
+              echo "Extracted event ID: $eventId"
+              echo "Expected event ID: $expectedDataEventId"
+
+              if [ "$eventId" == "$expectedDataEventId" ]; then
+                echo "test passed successfully"
+              else
+                echo "fail! unexpected event"
+                exit 1   
+              fi
+            displayName: 'Validate message in Kafka topic'
+  # --- END Validate event in Hub (UAT) --- #
 
